# Generated by Django 4.2.6 on 2023-11-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_payment_course_alter_payment_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
